### ISSUE TITLE
ヘッダー

### ISSUE THREAD

**Issue by xpadev-net** [May-Hackathon/BookScope-frontend#1]

**Comment by melmmmmmmm** [comment]
top、sign in、sign up
![header](https://github.com/May-Hackathon/BookScope-frontend/assets/108781228/31d637f5-a27f-4d60-a6fc-5232a67a2f45)

その他
![homeheader](https://github.com/May-Hackathon/BookScope-frontend/assets/108781228/c7b08979-badf-4dde-aaf1-28368b3cc5b0)
